<template>
    <BTableSimple striped hover>
      <BThead>
        <BTr>
          <BTh>Sensor</BTh>
          <BTh>Equipment</BTh>
          <BTh>Location</BTh>
          <BTh>Position</BTh>
          <BTh>State</BTh>
          <BTh>Alarm</BTh>
          <BTh>Temperature</BTh>
          <BTh>Temperature AVG</BTh>
          <BTh>Standard Deviation</BTh>
          <BTh>Quality</BTh>
          <BTh>RSSI</BTh>
          <BTh>Time Elapsed</BTh>
        </BTr>
      </BThead>
      <BTbody>
        <!-- Use v-for to loop through the data array -->
        <BTr v-for="(item, index) in tableData" :key="index">
          <BTd>{{ item.sensor }}</BTd>
          <BTd>{{ item.equipment }}</BTd>
          <BTd>{{ item.location }}</BTd>
          <BTd>{{ item.position }}</BTd>
          <BTd>{{ item.state }}</BTd>
          <BTd>{{ item.alarm }}</BTd>
          <BTd>{{ item.temperature }}</BTd>
          <BTd>{{ item.temperatureAvg }}</BTd>
          <BTd>{{ item.standardDeviation }}</BTd>
          <BTd>{{ item.quality }}</BTd>
          <BTd>{{ item.rssi }}</BTd>
          <BTd>{{ item.timeElapsed }}</BTd>
        </BTr>
      </BTbody>
      
    </BTableSimple>
  </template>
  
  <script>
  export default {
    name: 'CustomTable',
    data() {
      return {
        tableData: [
          {
            sensor: 'Sensor 1',
            equipment: 'Equipment 1',
            location: 'Location 1',
            position: 'Position 1',
            state: 'State 1',
            alarm: 'Alarm 1',
            temperature: 23,
            temperatureAvg: 24,
            standardDeviation: 2,
            quality: 'Good',
            rssi: -75,
            timeElapsed: '12:30',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },

          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },


          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          {
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },{
            sensor: 'Sensor 2',
            equipment: 'Equipment 2',
            location: 'Location 2',
            position: 'Position 2',
            state: 'State 2',
            alarm: 'Alarm 2',
            temperature: 21,
            temperatureAvg: 22,
            standardDeviation: 1,
            quality: 'Good',
            rssi: -70,
            timeElapsed: '14:15',
          },
          // Add more items as needed
        ],
      };
    },
  };
  </script>
  
  <style>
  /* Your table styles go here */
  </style>
  